site_name: Customies Docs
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Custom Item Guides: custom_item_guides.md
  - Custom Block Guides: custom_block_guides.md
  - Block Permutations: block_permutations.md
  - Custom Entity Guides: custom_entity_guides.md